/*
# Application wide actions.

Handle in all sub-reducers if necessary
*/

//account
export const APP_LOGIN_START = 'APP_LOGIN_START'
export const APP_LOGIN = 'APP_LOGIN'
export const APP_LOGIN_FAIL = 'APP_LOGIN_FAIL'
export const APP_GET_PROFILE_START = 'APP_GET_PROFILE_START'
export const APP_GET_PROFILE = 'APP_GET_PROFILE'
export const APP_GET_PROFILE_FAIL = 'APP_GET_PROFILE_FAIL'
export const APP_LOGOUT = 'APP_LOGOUT'

export const ADD_DIET_ITEM = 'ADD_DIET_ITEM'
export const ADD_SUPPLEMENT_ITEM = 'ADD_SUPPLEMENT_ITEM'
export const ADD_SELECTED_MEDICINE_ITEM = 'ADD_SELECTED_MEDICINE_ITEM'

//medications
export const MEDICATIONS_FETCH_START = 'MEDICATIONS_FETCH_START'
export const MEDICATIONS_DATA = 'MEDICATIONS_DATA'
export const MEDICATIONS_FETCH_FAIL = 'MEDICATIONS_FETCH_FAIL'
export const PATIENT_MEDICATIONS_FETCH_START = 'PATIENT_MEDICATIONS_FETCH_START'
export const PATIENT_MEDICATIONS_DATA = 'PATIENT_MEDICATIONS_DATA'
export const PATIENT_MEDICATIONS_FETCH_FAIL = 'PATIENT_MEDICATIONS_FETCH_FAIL'

//emr
export const EMR_FETCH_START = 'EMR_FETCH_START'
export const EMR_DATA = 'EMR_DATA'
export const EMR_FETCH_FAIL = 'EMR_FETCH_FAIL'

//diet
export const DIET_FETCH_START = 'DIET_FETCH_START'
export const DIET_DATA = 'DIET_DATA'
export const DIET_FETCH_FAIL = 'DIET_FETCH_FAIL'

//exercise
export const EXERCISE_FETCH_START = 'EXERCISE_FETCH_START'
export const EXERCISE_DATA = 'EXERCISE_DATA'
export const EXERCISE_FETCH_FAIL = 'EXERCISE_FETCH_FAIL'

//supllements
export const SUPPLEMENTS_FETCH_START = 'SUPPLEMENTS_FETCH_START'
export const SUPPLEMENTS_DATA = 'SUPPLEMENTS_DATA'
export const SUPPLEMENTS_FETCH_FAIL = 'SUPPLEMENTS_FETCH_FAIL'

//doctor
export const PATIENT_FETCH_START = 'PATIENT_FETCH_START'
export const PATIENT_DATA = 'PATIENT_DATA'
export const PATIENT_FETCH_FAIL = 'PATIENT_FETCH_FAIL'

//profile
export const PROFILE_FETCH_START = 'PROFILE_FETCH_START'
export const PROFILE_DATA = 'PROFILE_DATA'
export const PROFILE_FETCH_FAIL = 'PROFILE_FETCH_FAIL'

//prescription
export const PRESCRIPTION_FETCH_START = 'PRESCRIPTION_FETCH_START'
export const PRESCRIPTION_DATA = 'PRESCRIPTION_DATA'
export const PRESCRIPTION_FETCH_FAIL = 'PRESCRIPTION_FETCH_FAIL'

//patient
export const PATIENT_MEAL_START = 'PATIENT_MEAL_START'
export const PATIENT_MEAL_DATA = 'PATIENT_MEAL_DATA'
export const PATIENT_MEAL_FAIL = 'PATIENT_MEAL_FAIL'
export const PATIENT_SELF_MANAGEMENT_START = 'PATIENT_SELF_MANAGEMENT_START'
export const PATIENT_SELF_MANAGEMENT_FAIL = 'PATIENT_SELF_MANAGEMENT_FAIL'
export const PATIENT_SELF_MANAGEMENT_DATA = 'PATIENT_SELF_MANAGEMENT_DATA'
export const PATIENT_MEDICATION_START = 'PATIENT_MEDICATION_START'
export const PATIENT_MEDICATION_DATA = 'PATIENT_MEDICATION_DATA'
export const PATIENT_MEDICATION_FAIL = 'PATIENT_MEDICATION_FAIL'

//surveys
export const SURVEY_ALL_FETCH_START = 'SURVEY_ALL_FETCH_START'
export const SURVEY_ALL_DATA = 'SURVEY_ALL_DATA'
export const SURVEY_ALL_FETCH_FAIL = 'SURVEY_ALL_FETCH_FAIL'
export const SURVEY_QUESTIONS_FETCH_START = 'SURVEY_QUESTIONS_FETCH_START'
export const SURVEY_QUESTIONS_DATA = 'SURVEY_QUESTIONS_DATA'
export const SURVEY_QUESTIONS_FETCH_FAIL = 'SURVEY_QUESTIONS_FETCH_FAIL'
export const SURVEY_SUBMISSIONS_FETCH_START = 'SURVEY_SUBMISSIONS_FETCH_START'
export const SURVEY_SUBMISSIONS_FETCH_FAIL = 'SURVEY_SUBMISSIONS_FETCH_FAIL'
export const SURVEY_SUBMISSIONS_DATA = 'SURVEY_SUBMISSIONS_DATA'
export const POST_SURVEY_SUBMISSION_START = 'POST_SURVEY_SUBMISSION_START'
export const POST_SURVEY_SUBMISSION_FAIL = 'POST_SURVEY_SUBMISSION_FAIL'
export const POST_SURVEY_SUBMISSION_DATA = 'POST_SURVEY_SUBMISSION_DATA'
export const PUT_SURVEY_SUBMISSION_START = 'PUT_SURVEY_SUBMISSION_START'
export const PUT_SURVEY_SUBMISSION_FAIL = 'PUT_SURVEY_SUBMISSION_FAIL'
export const PUT_SURVEY_SUBMISSION_DATA = 'PUT_SURVEY_SUBMISSION_DATA'

//graphs
export const COVID_GRAPH_FETCH_START = 'COVID_GRAPH_FETCH_START'
export const COVID_GRAPH_DATA = 'COVID_GRAPH_DATA'
export const COVID_GRAPH_FETCH_FAIL = 'COVID_GRAPH_FETCH_FAIL'
export const CALORIES_BURNT_GRAPH_FETCH_START = 'CALORIES_BURNT_GRAPH_FETCH_START'
export const CALORIES_BURNT_GRAPH_FETCH_FAIL = 'CALORIES_BURNT_GRAPH_FETCH_FAIL'
export const CALORIES_BURNT_GRAPH_DATA = 'CALORIES_BURNT_GRAPH_DATA'
export const CALORIES_INTAKE_GRAPH_FETCH_START = 'CALORIES_INTAKE_GRAPH_FETCH_START'
export const CALORIES_INTAKE_GRAPH_FETCH_FAIL = 'CALORIES_INTAKE_GRAPH_FETCH_FAIL'
export const CALORIES_INTAKE_GRAPH_DATA = 'CALORIES_INTAKE_GRAPH_DATA'
export const SLEEP_GRAPH_FETCH_START = 'SLEEP_GRAPH_FETCH_START'
export const SLEEP_GRAPH_FETCH_FAIL = 'SLEEP_GRAPH_FETCH_FAIL'
export const SLEEP_GRAPH_DATA = 'SLEEP_GRAPH_DATA'