/*
# Application wide actions.

Handle in all sub-reducers if necessary
*/

//account
export const APP_LOGIN_START = 'APP_LOGIN_START'
export const APP_LOGIN = 'APP_LOGIN'
export const APP_LOGIN_FAIL = 'APP_LOGIN_FAIL'
export const APP_LOGOUT = 'APP_LOGOUT'

export const ADD_DIET_ITEM = 'ADD_DIET_ITEM'
export const ADD_SUPPLEMENT_ITEM = 'ADD_SUPPLEMENT_ITEM'
export const ADD_SELECTED_MEDICINE_ITEM = 'ADD_SELECTED_MEDICINE_ITEM'

//medications
export const MEDICATIONS_FETCH_START = 'MEDICATIONS_FETCH_START'
export const MEDICATIONS_DATA = 'MEDICATIONS_DATA'
export const MEDICATIONS_FETCH_FAIL = 'MEDICATIONS_FETCH_FAIL'

//emr
export const EMR_FETCH_START = 'EMR_FETCH_START'
export const EMR_DATA = 'EMR_DATA'
export const EMR_FETCH_FAIL = 'EMR_FETCH_FAIL'

//diet
export const DIET_FETCH_START = 'DIET_FETCH_START'
export const DIET_DATA = 'DIET_DATA'
export const DIET_FETCH_FAIL = 'DIET_FETCH_FAIL'

//supllements
export const SUPPLEMENTS_FETCH_START = 'SUPPLEMENTS_FETCH_START'
export const SUPPLEMENTS_DATA = 'SUPPLEMENTS_DATA'
export const SUPPLEMENTS_FETCH_FAIL = 'SUPPLEMENTS_FETCH_FAIL'

//doctor
export const PATIENT_FETCH_START = 'PATIENT_FETCH_START'
export const PATIENT_DATA = 'PATIENT_DATA'
export const PATIENT_FETCH_FAIL = 'PATIENT_FETCH_FAIL'

//profile
export const PROFILE_FETCH_START = 'PROFILE_FETCH_START'
export const PROFILE_DATA = 'PROFILE_DATA'
export const PROFILE_FETCH_FAIL = 'PROFILE_FETCH_FAIL'

//prescription
export const PRESCRIPTION_FETCH_START = 'PRESCRIPTION_FETCH_START'
export const PRESCRIPTION_DATA = 'PRESCRIPTION_DATA'
export const PRESCRIPTION_FETCH_FAIL = 'PRESCRIPTION_FETCH_FAIL'

