/*
# Application wide actions.

Handle in all sub-reducers if necessary
*/
export const ADD_DIET_ITEM = 'ADD_DIET_ITEM'
export const ADD_SUPPLEMENT_ITEM = 'ADD_SUPPLEMENT_ITEM'
export const ADD_SELECTED_MEDICINE_ITEM = 'ADD_SELECTED_MEDICINE_ITEM'
export const APP_LOGIN = 'APP_LOGIN'
export const APP_LOGOUT = 'APP_LOGOUT'

//medications
export const MEDICATIONS_FETCH_START = 'MEDICATIONS_FETCH_START'
export const MEDICATIONS_DATA = 'MEDICATIONS_DATA'
export const MEDICATIONS_FETCH_FAIL = 'MEDICATIONS_FETCH_FAIL'

//diet
export const DIET_FETCH_START = 'DIET_FETCH_START'
export const DIET_DATA = 'DIET_DATA'
export const DIET_FETCH_FAIL = 'DIET_FETCH_FAIL'

//supllements
export const SUPPLEMENTS_FETCH_START = 'SUPPLEMENTS_FETCH_START'
export const SUPPLEMENTS_DATA = 'SUPPLEMENTS_DATA'
export const SUPPLEMENTS_FETCH_FAIL = 'SUPPLEMENTS_FETCH_FAIL'


